version: '3'

services:
  web:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - C:\Users\USUARIO\OneDrive\Escritorio\Visual Studio\PaginaWebPrueba
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: usuarios
      MYSQL_USER: pablo
      MYSQL_PASSWORD: pablo123
      MYSQL_ROOT_PASSWORD: pablo123
    volumes:
      - ./datos_mysql:/var/lib/mysql